# define management endpoint, for instance: http://127.0.0.1:9091/api-gateway/health
# the management endpoint is ONLY available locally
# NOTE: set port to -1 for disabling all management endpoints
management:
    address: 127.0.0.1
    port: 9091
    context-path: /api-gateway

# define if which management endpoints should be available
endpoints:
    # [POST] shutdown the gateway
    # NOTE: needs to be enabled, used by service script.
    shutdown:
        enabled: true
    # [POST] restart the gateway
    restart:
        enabled: false
    # [GET] list all gateway configuration
    configprops:
        enabled: false
    # [GET] list the gateqway enviroment
    env:
        enabled: false

server:
  # define server port for gateway
  port: 9090
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: secret
#    key-password: password

# define orchestra parameters
orchestra:
  # define URL for orchestra central installation
  central:
    url: http://localhost:8080

  # by default we do not forward requests without a valid authentication token
  blockUnauthorized : true

  # use 'password-encoder' script in 'bin' folder script for encoding new password.
  # use 'api-token-generator' script in 'bin' folder  for generating new token.
  api_tokens:
    c7a1331a-32d-11e5-bf7f-feff819acdc9f:
      user: superadmin
      passwd: dWxhbg==
    d0516eee-a32d-11e5-bf7f-feff819cdc9f:
      user: mobile
      passwd: dWxhbg==
  
  # use checksum validation for mobile requests
  enableChecksum: true
  
  # define which proxy routes where checksum validation will be applied
  checksumRoutes:  
    my_visit_delete_deprecated:
      parameter: ticket
    my_visit_delete:
      parameter: ticket
    my_visit_position:
      parameter: visit

cache:
  # by default the cache metrics connector is only accessable from local machine
  allowCacheMetricsFromAllHosts: false
  # if true, all requests not matching the rules in cacheRoutes will get cached in the default cache
  useDefaultCache: true
  # name of cache in ehcache configuration
  defaultCacheName: request
  # define if unique cache is used for URL query parameters.
  defaultCacheUniquePerQueryParameter: false

  cacheRoutes:
    services:
      # name of cache in ehcache configuration
      cacheName: serviceCache
      # REST path pattern matching
      match: /services
      # defines which zuul routes to apply caching to
      routes: mobile_service_v1, mobile_service_v2
      # configure if the cache should store a unique value per query parameter string (default false)
      uniquePerQueryParameter : false
    mobileServices:
      cacheName: serviceCache
      match: .*
      routes: custom_mobile_services
    visits:
      cacheName: visitInQueueCache
      match: /branches/[0-9]+/queues/[0-9]+/visits[/]?
      routes: servicepoint_api
    events:
      cacheName: eventInQueueCache
      match: /branches/[0-9]+/visits/[0-9]+/events[/]?
      routes: my_visit_last_queue_event

urlDecodeFilter:
  enabled: false
  encryptionKey: ApiGw

# Details logging if routing fails. This is off by default not to flood logs if orchestra is down
logZuulExceptions : false

# define routes exposed via zuul proxy     
zuul:
  routes:
    appointment_api:
       path: /rest/appointment/**
       url: ${orchestra.central.url}/qsystem/rest/appointment
    digitalsignage_api:
        path: /rest/digitalsignage/**
        url: ${orchestra.central.url}/qsystem/rest/digitalsignage
    entrypoint_api:
        path: /rest/entrypoint/**
        url: ${orchestra.central.url}/qsystem/rest/entrypoint
    servicepoint_api:
        path: /rest/servicepoint/**
        url: ${orchestra.central.url}/qsystem/rest/servicepoint
    management_information:
        path: /rest/managementinformation/**
        url: ${orchestra.central.url}/qsystem/rest/managementinformation
    mobile_service_v2:
        path: /rest/mobile/v2/**
        url: ${orchestra.central.url}/qsystem/mobile/rest/v2
    mobile_service_v1:
        path: /rest/mobile/**
        url: ${orchestra.central.url}/qsystem/mobile/rest
    calendar_internal_api:
        path: /rest/calendar-backend/api/**
        url: ${orchestra.central.url}/calendar-backend/api
    calendar_public_api:
        path: /rest/calendar-backend/public/api/**
        url: ${orchestra.central.url}/calendar-backend/public/api

    # custom mobile service example
    # (authentication against mobile)

    # get services for branch - /MobileTicket/branches/[branchId]/services
    custom_mobile_branches:
      path: /MobileTicket/branches/**
      url: ${orchestra.central.url}/qsystem/mobile/rest/v2/branches

    custom_mobile_services:
      path: /MobileTicket/services/**
      url : ${orchestra.central.url}/qsystem/mobile/rest/v2/services

    # Mobile ticket -authentication against mobile - routes protected by checksum
    my_visit_delete_deprecated:
      path: /MobileTicket/MyVisit/branches/*/ticket/**
      url: ${orchestra.central.url}/qsystem/mobile/rest/v2/branches

    my_visit_delete:
      path: /MobileTicket/MyVisit/branches/*/visit/**
      url: ${orchestra.central.url}/qsystem/mobile/rest/v2/branches/*/ticket

    my_visit_position:
      path: MobileTicket/MyVisit/Position/branches/*/visit/**
      url: ${orchestra.central.url}/qsystem/mobile/rest/v2/branches
    

    # Note:
    # get nearest branches - /geo/services/[serviceId]/nearestbranches
    # get branches for service - /MobileTicket/services/[serviceId]/branches/
    # issue ticket - /MobileTicket/services/[serviceId]/branches/[branchId]/ticket/issue

    # custom MyVisit example
    # (authentication against orchestra)

    # get position in queue - /MobileTicket/MyVisit/Position/branches/[branchId]/queues/[queueId]/visits?visitId=[visitId]
    my_visit_queue_position:
      path: /MobileTicket/MyVisit/Position/**
      url: ${orchestra.central.url}/qsystem/rest/servicepoint

    # get last event for visit - /MobileTicket/MyVisit/LastEvent/branches/[branchId]/visits/[visitId]/events?visitId=[visitId]
    my_visit_last_queue_event:
      path: /MobileTicket/MyVisit/LastEvent/**
      url: ${orchestra.central.url}/qsystem/rest/servicepoint

    mobile_decoding:
      path: /mobileEnc/**
      url: dummy

    # get current status of visit - /MobileTicket/MyVisit/CurrentStatus/branches/[branchId]/visits/[visitId]?checksum=[checksum]
    my_visit_current_status:
      path: /MobileTicket/MyVisit/CurrentStatus/**
      url: ${orchestra.central.url}/qsystem/mobile/rest/v2

# These URLs are used internally for fetching branches and branches for services but these should normally not be changed.
geoService:
  branches_url: ${orchestra.central.url}/qsystem/mobile/rest/v2/branches?longitude=0&latitude=0&radius=2147483647
  service_branches_url: ${orchestra.central.url}/qsystem/mobile/rest/v2/services/{serviceId}/branches?longitude=0&latitude=0&radius=2147483647

currentStatus:
  visits_on_branch_url: ${orchestra.central.url}/qsystem/mobile/rest/v2/branches/{branchId}/visits
